export const CURRENCIES = {
  // Major / Most Traded
  USD: { name: 'US Dollar', symbol: '$', flag: '🇺🇸' },
  EUR: { name: 'Euro', symbol: '€', flag: '🇪🇺' },
  JPY: { name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵' },
  GBP: { name: 'British Pound', symbol: '£', flag: '🇬🇧' },
  AUD: { name: 'Australian Dollar', symbol: 'A$', flag: '🇦🇺' },
  CAD: { name: 'Canadian Dollar', symbol: 'C$', flag: '🇨🇦' },
  CHF: { name: 'Swiss Franc', symbol: 'Fr', flag: '🇨🇭' },
  CNY: { name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳' },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$', flag: '🇭🇰' },
  NZD: { name: 'New Zealand Dollar', symbol: 'NZ$', flag: '🇳🇿' },
  SEK: { name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪' },
  KRW: { name: 'South Korean Won', symbol: '₩', flag: '🇰🇷' },
  SGD: { name: 'Singapore Dollar', symbol: 'S$', flag: '🇸🇬' },
  NOK: { name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴' },
  MXN: { name: 'Mexican Peso', symbol: '$', flag: '🇲🇽' },
  INR: { name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳' },
  RUB: { name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺' },
  ZAR: { name: 'South African Rand', symbol: 'R', flag: '🇿🇦' },
  TRY: { name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷' },
  BRL: { name: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷' },
  TWD: { name: 'Taiwan Dollar', symbol: 'NT$', flag: '🇹🇼' },
  DKK: { name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰' },
  PLN: { name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱' },
  THB: { name: 'Thai Baht', symbol: '฿', flag: '🇹🇭' },
  IDR: { name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩' },
  HUF: { name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺' },
  CZK: { name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿' },
  ILS: { name: 'Israeli Shekel', symbol: '₪', flag: '🇮🇱' },
  CLP: { name: 'Chilean Peso', symbol: '$', flag: '🇨🇱' },
  PHP: { name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭' },
  AED: { name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪' },
  COP: { name: 'Colombian Peso', symbol: '$', flag: '🇨🇴' },
  SAR: { name: 'Saudi Riyal', symbol: '﷼', flag: '🇸🇦' },
  MYR: { name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾' },
  RON: { name: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴' },

  // Asia-Pacific
  VND: { name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳' },
  BDT: { name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩' },
  PKR: { name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰' },
  LKR: { name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰' },
  NPR: { name: 'Nepalese Rupee', symbol: '₨', flag: '🇳🇵' },
  MMK: { name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲' },
  KHR: { name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭' },
  LAK: { name: 'Lao Kip', symbol: '₭', flag: '🇱🇦' },
  BND: { name: 'Brunei Dollar', symbol: 'B$', flag: '🇧🇳' },
  MNT: { name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳' },
  KZT: { name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿' },
  UZS: { name: 'Uzbekistani Som', symbol: 'сум', flag: '🇺🇿' },
  AFN: { name: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫' },

  // Middle East
  QAR: { name: 'Qatari Riyal', symbol: '﷼', flag: '🇶🇦' },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: '🇰🇼' },
  BHD: { name: 'Bahraini Dinar', symbol: 'BD', flag: '🇧🇭' },
  OMR: { name: 'Omani Rial', symbol: '﷼', flag: '🇴🇲' },
  JOD: { name: 'Jordanian Dinar', symbol: 'JD', flag: '🇯🇴' },
  LBP: { name: 'Lebanese Pound', symbol: 'L£', flag: '🇱🇧' },
  IQD: { name: 'Iraqi Dinar', symbol: 'ع.د', flag: '🇮🇶' },
  IRR: { name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷' },

  // Europe
  HRK: { name: 'Croatian Kuna', symbol: 'kn', flag: '🇭🇷' },
  BGN: { name: 'Bulgarian Lev', symbol: 'лв', flag: '🇧🇬' },
  ISK: { name: 'Icelandic Krona', symbol: 'kr', flag: '🇮🇸' },
  RSD: { name: 'Serbian Dinar', symbol: 'din', flag: '🇷🇸' },
  BAM: { name: 'Bosnia-Herzegovina Mark', symbol: 'KM', flag: '🇧🇦' },
  MKD: { name: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰' },
  ALL: { name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱' },
  MDL: { name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩' },
  UAH: { name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦' },
  BYN: { name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾' },
  GEL: { name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪' },
  AMD: { name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲' },
  AZN: { name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿' },

  // Americas
  ARS: { name: 'Argentine Peso', symbol: '$', flag: '🇦🇷' },
  PEN: { name: 'Peruvian Sol', symbol: 'S/', flag: '🇵🇪' },
  UYU: { name: 'Uruguayan Peso', symbol: '$U', flag: '🇺🇾' },
  PYG: { name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾' },
  BOB: { name: 'Bolivian Boliviano', symbol: 'Bs.', flag: '🇧🇴' },
  VES: { name: 'Venezuelan Bolívar', symbol: 'Bs.S', flag: '🇻🇪' },
  DOP: { name: 'Dominican Peso', symbol: 'RD$', flag: '🇩🇴' },
  GTQ: { name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹' },
  CRC: { name: 'Costa Rican Colón', symbol: '₡', flag: '🇨🇷' },
  HNL: { name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳' },
  JMD: { name: 'Jamaican Dollar', symbol: 'J$', flag: '🇯🇲' },
  TTD: { name: 'Trinidad & Tobago Dollar', symbol: 'TT$', flag: '🇹🇹' },

  // Africa
  NGN: { name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬' },
  KES: { name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪' },
  GHS: { name: 'Ghanaian Cedi', symbol: 'GH₵', flag: '🇬🇭' },
  TZS: { name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿' },
  UGX: { name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬' },
  ETB: { name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹' },
  MAD: { name: 'Moroccan Dirham', symbol: 'د.م.', flag: '🇲🇦' },
  EGP: { name: 'Egyptian Pound', symbol: '£', flag: '🇪🇬' },
  DZD: { name: 'Algerian Dinar', symbol: 'دج', flag: '🇩🇿' },
  TND: { name: 'Tunisian Dinar', symbol: 'DT', flag: '🇹🇳' },
  XOF: { name: 'West African CFA Franc', symbol: 'CFA', flag: '🌍' },
  XAF: { name: 'Central African CFA Franc', symbol: 'CFA', flag: '🌍' },
  MUR: { name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺' },

  // Oceania
  FJD: { name: 'Fijian Dollar', symbol: 'FJ$', flag: '🇫🇯' },
  PGK: { name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬' },

  // Additional Popular
  MZN: { name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿' },
  ZMW: { name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲' },
  RWF: { name: 'Rwandan Franc', symbol: 'Fr', flag: '🇷🇼' },
  CDF: { name: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩' },
} as const

export type CurrencyCode = keyof typeof CURRENCIES
export type CurrencyMeta = (typeof CURRENCIES)[CurrencyCode]

export const TOP_CURRENCY_CODES = Object.keys(CURRENCIES) as CurrencyCode[]
